import { createClient } from "@/lib/supabase/server";
import type { NfcTag } from "@/types/nfc";

/**
 * Data access for NFC tags. RLS ensures only workspace members can read and
 * only owners can manage.
 */

/** Get all NFC tags in a workspace. */
export async function getNfcTags(workspaceId: string): Promise<NfcTag[]> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("nfc_tags")
    .select("*")
    .eq("workspace_id", workspaceId)
    .order("created_at", { ascending: true });

  if (error) throw error;
  return (data ?? []) as NfcTag[];
}

/** Create a new NFC tag. The secret_token is generated by the database. */
export async function createNfcTag(
  workspaceId: string,
  shoppingListId: string,
  name: string,
): Promise<NfcTag> {
  const supabase = await createClient();
  const secretToken = generateSecretToken();
  const { data, error } = await supabase
    .from("nfc_tags")
    .insert({
      workspace_id: workspaceId,
      shopping_list_id: shoppingListId,
      name,
      secret_token: secretToken,
    })
    .select("*")
    .single();

  if (error) throw error;
  return data as NfcTag;
}

/** Update an NFC tag's name, enabled status, or associated list. */
export async function updateNfcTag(
  tagId: string,
  patch: Partial<Pick<NfcTag, "name" | "enabled" | "shopping_list_id">>,
): Promise<void> {
  const supabase = await createClient();
  const { error } = await supabase
    .from("nfc_tags")
    .update(patch)
    .eq("id", tagId);

  if (error) throw error;
}

/** Delete an NFC tag. */
export async function deleteNfcTag(tagId: string): Promise<void> {
  const supabase = await createClient();
  const { error } = await supabase.from("nfc_tags").delete().eq("id", tagId);
  if (error) throw error;
}

/** Generate a 32-char hex secret token for an NFC tag. */
function generateSecretToken(): string {
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);
  return Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
}
