import { createClient } from "@/lib/supabase/server";
import type {
  CreateInvitationInput,
  WorkspaceInvitation,
} from "@/types/invitation";

/**
 * Data access for workspace invitations. RLS ensures only members can read
 * and only owners can manage.
 */

/** Get all invitations for a workspace. */
export async function getInvitations(
  workspaceId: string,
): Promise<WorkspaceInvitation[]> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("workspace_invitations")
    .select("*")
    .eq("workspace_id", workspaceId)
    .order("created_at", { ascending: false });

  if (error) throw error;
  return (data ?? []) as WorkspaceInvitation[];
}

/** Create a new invitation. The token is generated by the database. */
export async function createInvitation(
  createdBy: string,
  input: CreateInvitationInput,
): Promise<WorkspaceInvitation> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("workspace_invitations")
    .insert({
      workspace_id: input.workspaceId,
      created_by: createdBy,
      role: input.role ?? "EDITOR",
      expires_at: input.expiresAt ?? null,
      max_uses: input.maxUses ?? null,
    })
    .select("*")
    .single();

  if (error) throw error;
  return data as WorkspaceInvitation;
}

/** Revoke an invitation (set revoked_at). */
export async function revokeInvitation(invitationId: string): Promise<void> {
  const supabase = await createClient();
  const { error } = await supabase
    .from("workspace_invitations")
    .update({ revoked_at: new Date().toISOString() })
    .eq("id", invitationId);

  if (error) throw error;
}
